### ISSUE TITLE
Please consider an explicit license for the repo

### ISSUE THREAD

**Issue by mpenning** [verbosemode/netcliparsers#1]
Hi Jochen,

How is this repo licensed?  If it's licensed [MIT](http://en.wikipedia.org/wiki/MIT_License), then that's permissive and I can almost do anything with it; however, if it's licensed GPL, derived works must be licensed the same way and published.  I'm interested in potentially integrating this with other libraries, but I'd like to understand the terms and conditions.  If you're not sure which license to use, there is a pretty good guide here:

http://choosealicense.com/

Even if you just declare it as [WTFPL](http://www.wtfpl.net/), that's [better than no explicit licensing terms](http://lu.is/blog/2013/01/27/taking-post-open-source-seriously-as-a-statement-about-copyright-law/)

**Comment by verbosemode** [comment]
Hello Mike,

thanks for your feedback and thanks for the wonderful ciscoconfparse.

Normally I'm all about free software and GPL, but every now and then people complain about it. However I tend towards GPLv3. But I'll read through the link you sent and make a decision afterwards.

Best regards,

Jochen

**Comment by verbosemode** [comment]
I've decided to go with GPLv3. Fixed in d9791c0c307e74c1827628cc5703c7f05a698324
